### PR TITLE
[ENH] Add an optional connectivity argument for support of 8-connectedness in 2D and 18, 26-connectedness in 3D

### PR DESCRIPTION
**Pull request by turtleizzy**

### CODE REVIEW

**Comment by masadcv** [comment]
Hi @turtleizzy ,

Many thanks for your contribution!! I have briefly gone through the code, and all looks good to me. I will do some testing this weekend and merge this PR afterwards..

**Comment by masadcv** [comment]
Hi @turtleizzy ,
I have reviewed this now and all looks good to me. Many thanks for contributing and improving the library. 
 
May I ask if it is possible for you to add a simple example showing usage of different connectivities to new users?
It could be incorporated within `demo_maxflow.py` at the root directory. Or you can add a new python script, whichever you prefer.

**Review by masadcv — APPROVED** [review]

**Comment by masadcv** [comment]
Do you also want to add these changes to numpymaxflow?

**Comment by turtleizzy** [comment]
> Do you also want to add these changes to numpymaxflow?

Sure. I will create another pr for this.

**Pull request merged**
